name = {
    weapon = {

        {'Weapon_advancedrifle', 'WEAPON_ADVANCEDRIFLE'},
        {'Weapon_appistol', 'WEAPON_APPISTOL'},
        {'Weapon_assaultrifle', 'WEAPON_ASSAULTRIFLE'},
        {'Weapon_assaultrifle_mk2', 'WEAPON_ASSAULTRIFLE_MK2'},
        {'Weapon_assaultshotgun', 'WEAPON_ASSAULTSHOTGUN'},
        {'Weapon_assaultsmg', 'WEAPON_ASSAULTSMG'},
        {'Weapon_bat', 'WEAPON_BAT'},
        {'Weapon_battleaxe', 'WEAPON_BATTLEAXE'},
        {'Weapon_bottle', 'WEAPON_BOTTLE'},
        {'Weapon_bullpuprifle', 'WEAPON_BULLPUPRIFLE'},
        {'Weapon_bullpuprifle_mk2', 'WEAPON_BULLPUPRIFLE_MK2'},
        {'Weapon_bullpupshotgun', 'WEAPON_BULLPUPSHOTGUN'},
        {'Weapon_bzgas', 'WEAPON_BZGAS'},
        {'Weapon_carbinerifle', 'WEAPON_CARBINERIFLE'},
        {'Weapon_carbinerifle_mk2', 'WEAPON_CARBINERIFLE_MK2'},
        {'Weapon_combatmg', 'WEAPON_COMBATMG'},
        {'Weapon_combatmg_mk2', 'WEAPON_COMBATMG_MK2'},
        {'Weapon_combatpdw', 'WEAPON_COMBATPDW'},
        {'Weapon_combatpistol', 'WEAPON_COMBATPISTOL'},
        {'Weapon_crowbar', 'WEAPON_CROWBAR'},
        {'Weapon_doubleaction', 'WEAPON_DOUBLEACTION'},
        {'Weapon_flaregun', 'WEAPON_FLAREGUN'},
        {'Weapon_flashlight', 'WEAPON_FLASHLIGHT'},
        {'Weapon_golfclub', 'WEAPON_GOLFCLUB'},
        {'Weapon_grenade', 'weapon_grenade'},
        {'Weapon_hatchet', 'WEAPON_HATCHET'},
        {'Weapon_heavypistol', 'WEAPON_HEAVYPISTOL'},
        {'Weapon_heavyshotgun', 'WEAPON_HEAVYSHOTGUN'},
        {'Weapon_heavysniper', 'WEAPON_HEAVYSNIPER'},
        {'Weapon_heavysniper_mk2', 'WEAPON_HEAVYSNIPER_MK2'},
        {'Weapon_knife', 'WEAPON_KNIFE'},
        {'Weapon_knuckle', 'WEAPON_KNUCKLE'},
        {'Weapon_machete', 'WEAPON_MACHETE'},
        {'Wepon_machinepistol', 'WEAPON_MACHINEPISTOL'},
        {'Weapon_marksmanpistol', 'WEAPON_MARKSMANPISTOL'},
        {'Weapon_Marksmanrifle', 'WEAPON_MARKSMANRIFLE'},
        {'Weapon_Marksmanrifle_mk2', 'WEAPON_MARKSMANRIFLE_MK2'},
        {'Weapon_mg', 'WEAPON_MG'},
        {'Weapon_microsmg', 'WEAPON_MICROSMG'},
        {'Weapon_minismg', 'WEAPON_MINISMG'},
        {'Weapon_molotov', 'weapon_molotov'},
        {'Weapon_musket', 'WEAPON_MUSKET'},
        {'Weapon_nightstick', 'WEAPON_NIGHTSTICK'},
        {'Weapon_petrolcan', 'WEAPON_PETROLCAN'},
        {'Weapon_petrolcan', 'WEAPON_PETROLCAN'},
        {'Weapon_pistol', 'WEAPON_PISTOL'},
        {'Weapon_pistol_mk2', 'WEAPON_PISTOL_MK2'},
        {'Weapon_pistol50', 'WEAPON_PISTOL50'},
        {'Weapon_pumpshotgun', 'WEAPON_PUMPSHOTGUN'},
        {'Weapon_pumpshotgun_mk2', 'WEAPON_PUMPSHOTGUN_MK2'},
        {'Weapon_revolver', 'WEAPON_REVOLVER'},
        {'Weapon_sawnoffshotgun', 'WEAPON_SAWNOFFSHOTGUN'},
        {'Weapon_smg', 'WEAPON_SMG'},
        {'Weapon_smg_mk2', 'WEAPON_SMG_MK2'},
        {'Weapon_smokegrenade', 'WEAPON_SMOKEGRENADE'},
        {'WEAPON_sniperrifle', 'WEAPON_SNIPERRIFLE'},
        {'Weapon_snspistol', 'WEAPON_SNSPISTOL'},
        {'Weapon_snspistol_mk2', 'WEAPON_SNSPISTOL_MK2'},
        {'Weapon_specialcarbine', 'WEAPON_SPECIALCARBINE'},
        {'Weapon_specialcarbine_mk2', 'WEAPON_SPECIALCARBINE_MK2'},
        {'Weapon_stickybomb', 'Weapon_stickybomb'},
        {'Weapon_stungun', 'WEAPON_STUNGUN'},
        {'Weapon_switchblade', 'WEAPON_SWITCHBLADE'},
        {'Weapon_vintagepistol', 'WEAPON_VINTAGEPISTOL'},

    }
}

ammo = {
    Weapon = {

        {'Ammo-9', 'ammo-9'},
        {'Ammo-44', 'ammo-44'},
        {'Ammo-musket', 'ammo-musket'},
        {'Ammo-rifle', 'ammo-rifle'},
        {'Ammo-rifle2', 'ammo-rifle2'},
        {'Ammo-shotgun', 'ammo-shotgun'},
        {'Ammo-sniper', 'ammo-sniper'},

    }
}
